# Generated by Django 2.1.5 on 2020-08-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pf_home', '0002_auto_20200825_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmessage',
            name='code',
            field=models.PositiveSmallIntegerField(blank=True, default=91),
        ),
        migrations.AlterField(
            model_name='clientmessage',
            name='phone',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
