# Generated by Django 2.1.5 on 2020-08-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pf_home', '0004_auto_20200825_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmessage',
            name='code',
            field=models.CharField(blank=True, default='91', max_length=2),
        ),
    ]
