# Generated by Django 2.1.5 on 2020-08-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pf_home', '0005_auto_20200825_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
